### PR TITLE
added name

### PR DESCRIPTION
**Pull request by AdaezeIkemefuna**

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
Please just your name alone should be touched.

**Comment by AdaezeIkemefuna** [comment]
I touched only my name o. i pulled like you said, created a new branch and added my name. then i pushed to the new branch and created a pr from there. I don't know why i still had a little conflict but i only removed the arrows to resolve it.

**Comment by Oluwasetemi** [comment]
Can you close this one and create a fresh PR.

**Comment by Oluwasetemi** [comment]
Close this one and pull the latest code.

**Comment by AdaezeIkemefuna** [comment]
Okay

**Pull request closed without merging**
