### PR TITLE
from peter

### PR DESCRIPTION
**Pull request by CFCIfe**

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by CFCIfe** [comment]
I followed the commands, I don't know why there was force merge. I used the commands on the README. You can check the status of my forked repo

**Comment by Oluwasetemi** [comment]
@tobisupreme can you look into this.

**Comment by CFCIfe** [comment]
image
This is my view. I apologize for the way it was forced on your end. I am deleting the forked repo and local content.

**Comment by tobisupreme** [comment]
🙏

**Comment by Oluwasetemi** [comment]
Do you know what the issue is @tobisupreme ?

**Comment by tobisupreme** [comment]
No, I don't. 

I remember that when I discarded one of the branches that I opened a pull request with, I had a similar message. [!](https://i.ibb.co/FhxdN1z/Screenshot-from-2022-08-15-14-52-05.png)

Merged with 0 commits

**Pull request merged**
