### PR TITLE
Added Eloghosa to list

### PR DESCRIPTION
**Pull request by mynameissaraah**
Added Eloghosa to list

### CODE REVIEW

**Review by Succynice — COMMENTED** [review]
can you update your code by pulling the latest changes from the upstream, then push again.

```sh
git pull upstream main

git push origin main
```

**Comment by Oluwasetemi** [comment]
@tobisupreme we have another forced merge here as well.

**Comment by tobisupreme** [comment]
They most likely discarded this branch. It is merged, but with 0 commits

**Comment by Oluwasetemi** [comment]
So something on the README is what I fear is causing this.

**Comment by tobisupreme** [comment]
Probably. It seems this is a non issue. I think that a workaround will be to come and close the pull request before discarding the branch.
Either ways, its the same end result 😅

**Comment by mynameissaraah** [comment]
Is there something I need to do?

**Comment by Oluwasetemi** [comment]
Give me sometimes I will tell you what to do.

**Pull request merged**
