### PR TITLE
edited

### PR DESCRIPTION
**Pull request by EdisCode**

### CODE REVIEW

**Comment by Succynice** [comment]
Elizabeth- added my name successfully by TemmyLizzy · Pull Request #163 · Oluwasetemi_altschool-opensource-names - Google Chrome 8_8_2022 9_51_54 PM

can you remove the unnecessary lines and the space

**Comment by EdisCode** [comment]
There is no line or space here

**Comment by EdisCode** [comment]
check again

**Review by Succynice — APPROVED** [review]
you rock Ekenem!

**Comment by EdisCode** [comment]
thank you

**Pull request merged**
