### PR TITLE
added name to names.txt

### PR DESCRIPTION
**Pull request by Favour-Cay**
## added Favour Keshi Chiamaka to names.txt

### CODE REVIEW

**Comment by tobisupreme** [comment]
Please make a separate branch for this change 🙏

Check the readme for instructions

**Comment by Favour-Cay** [comment]
> Please make a separate branch for this change 🙏
> 
> Check the readme for instructions

ohh ,i didnt do it correctly?

**Comment by tobisupreme** [comment]
Thank you for your PR! Please [make a branch](https://github.com/Oluwasetemi/altschool-opensource-names/#make-a-branch) for your change 🙏

**Comment by tobisupreme** [comment]
> > Please make a separate branch for this change pray
> > Check the readme for instructions
> 
> ohh ,i didnt do it correctly?

Just a slight oversight 😅
The only thing left is a separate branch

**Review by tobisupreme — APPROVED** [review]

**Pull request merged**
