### PR TITLE
Added my name

### PR DESCRIPTION
**Pull request by grafikii**

### CODE REVIEW

**Comment by Succynice** [comment]
pls can you update your code

**Comment by grafikii** [comment]
Again, I wonder why this keeps happening, everything seems fine in the forked repo after comit. I wonder what could be wrong

**Comment by Succynice** [comment]
The thing is every new merge creates a new version of upstream. This means that all PRs before the most recent merge become out of date, resulting to a conflict. And a PR that has conflict can't be merged unless it's resolved

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Pull request merged**
