### PR TITLE
Added my name Ibimina Hart

### PR DESCRIPTION
**Pull request by ibimina**

### CODE REVIEW

**Comment by ibimina** [comment]
resolved conflict

**Comment by Succynice** [comment]
sorry your code is still behind, can you update your code to get the latest changes

```sh
git pull upstream main

git push origin main
```

**Comment by ibimina** [comment]
just updated my code

**Comment by Succynice** [comment]
altschool-opensource-names_names txt at main · Oluwasetemi_altschool-opensource-names - Google Chrome 8_8_2022 6_58_55 PM


as you can see the last number in the latest code is 47, while you have 28 in your name.text.

you can update to the latest by pulling from the upstream of the original repository

**Comment by ibimina** [comment]
what of now? I am see 48 names in my name.txt. I don't now what I am doing wrong

**Comment by ibimina** [comment]
recent update

**Review by Succynice — APPROVED** [review]
you're doing well

**Comment by ibimina** [comment]
Thanks

**Pull request merged**
