### PR TITLE
Added my name

### PR DESCRIPTION
**Pull request by altinuke**
In the spirit of learning how github works, I have added my name!

### CODE REVIEW

**Review by Succynice — COMMENTED** [review]
pls update your code

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Oluwasetemi** [comment]
Kingsley Umujeyan is repeated from your PR. Can you look into this?

**Comment by Oluwasetemi** [comment]
Still have some issues here.
image

It will add your name and remove 3 other names.

**Comment by altinuke** [comment]
@Oluwasetemi Please, review again. Thank you

**Pull request merged**
