### PR TITLE
Added a name

### PR DESCRIPTION
**Pull request by Angel-ifechukwu**

### CODE REVIEW

**Comment by tobisupreme** [comment]
Hello Angel!

Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/).

To enable me to do this, READ the README again carefully, update your code with the latest and push the update. I am here for you for the next 6 hours before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Succynice** [comment]
Sorry I have to close this PR, kindly update your code and initiate a fresh PR

Cheers 🥂

**Comment by Angel-ifechukwu** [comment]
Good morning Success,
I'm just seeing this mail now and I want to know if I can still merge and
push this request.
I'd appreciate your immediate response.


Thanks☺

**Comment by Angel-ifechukwu** [comment]
I'm confused and i don't know where to start from. I'd appreciate if you could guide me on what to do

**Comment by tobisupreme** [comment]
Okay. I've sent you a message on Slack

**Pull request closed without merging**
