### PR TITLE
Added search contributors feature

### PR DESCRIPTION
**Pull request by omobolajisonde**
Hi, added my name in the name.txt file and wrote the search contributor feature. Anticipating your review.

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by tobisupreme** [comment]
Hi Jibola!

Thank you for the search feature. I request that you separate the commits into different PRs. One for adding names, the other for the search feature.

You can remove one from this PR and open a new one. If you would like, I can remove one on your behalf too.

Thank you so much 🥳

**Comment by omobolajisonde** [comment]
> Thank you for the search feature.

Wow, wish I had seen this earlier. I just requested another PR, doing the same thing.

**Comment by tobisupreme** [comment]
Thank you! Sorry for the mix up 😅

If you don't mind, I will edit the original message 😤  😀

Someone else will handle the PR with the search feature 🙏

**Pull request merged**
