### PR TITLE
added Precious Eseose Agboinghale to the list of names

### PR DESCRIPTION
**Pull request by Oat-mea**

### CODE REVIEW

**Review by tobisupreme — APPROVED** [review]

**Comment by tobisupreme** [comment]
Please resolve merge conflicts 🙏🏽

**Comment by Oat-mea** [comment]
Done!😊

**Comment by Oat-mea** [comment]
Tobi, please I'm confused 🙏🏾

**Comment by tobisupreme** [comment]
Okay. What is unclear?

**Comment by Oat-mea** [comment]
You said merged #739 into main and I don't understand that. Sorry.

**Comment by tobisupreme** [comment]
Eh, don't apologise 😅

You made a fork of this project with the intention of making changes to it.

That is the reason you created an isolated branch (as per the instructions in the `README.md`), to make your changes.

When you opened a pull request, you initiated the final stage of adding your changes to the original repo.

Because I am a maintainer of the original repo, I have the privilege of merging the changes of contributors, like you.

**Comment by tobisupreme** [comment]
Your pull request has an id of #739. The original repository main branch is main.

Now, your changes have been merged into main. If you check the `names.txt`, you will see that your name is there. That's why your pull request has been closed

**Comment by Oat-mea** [comment]
Oh okay, I understand now, thank you so much, Tobi. Is there anything I
have to do at my end?

**Comment by tobisupreme** [comment]
No. All __transactions__ are now settled and you are a contributor to this project 🚀

**Comment by thereson** [comment]
First pull request

**Pull request merged**
