### PR TITLE
Updated name

### PR DESCRIPTION
**Pull request by St-Pardon**

### CODE REVIEW

**Comment by oseunabiola** [comment]
Can you please update your code by pulling the latest code from the original repo?

```sh

git pull upstream main

git push origin main

```

**Comment by St-Pardon** [comment]
I've just done that and resolved conflict.

**Comment by Succynice** [comment]
can you repeat the process one more time

**Comment by Oluwasetemi** [comment]
image

We have updated the code and your fork is out of date. Name list is one 41 and your is on 29. Sorry for the back and forth

**Comment by St-Pardon** [comment]
Okay, I've synced to update the branch

**Pull request merged**
