### PR TITLE
Request to merge

### PR DESCRIPTION
**Pull request by KingCephas2022**
Please merge

### CODE REVIEW

**Comment by tobisupreme** [comment]
Peter, your commit includes 6 files. Please split these changes into different branches and open a separate pull request per change.

For instance, a branch `adding-name` for adding your name. Another branch `modifying-readme` for making changes to the readme, etc. 🙏

**Comment by Oluwasetemi** [comment]
image

Your file changes should just be one file names.txt and it should contain a single change with just your name.

**Comment by Oluwasetemi** [comment]
Please can you close this PR and create another one?

**Comment by Oluwasetemi** [comment]
Please close and create new one. The file changes here is too much. If you don't know how kindly read the README.

**Comment by Succynice** [comment]
@KingCephas2022 the changes in this PR is too much and may not be intentional, pls kindly close this PR and create a new one (editing only the name.txt) as advised. NB the README can guide you on how to.

If you let me, I can equally assist you in closing this PR maybe if you can't do that from your end.

**Pull request closed without merging**
