### PR TITLE
name added

### PR DESCRIPTION
**Pull request by oyindamolaWbCode**

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
@oyindamolaWbCode Omoregbe Daniel is going to be duplicated. Can you fix this. As we are ready to merge this.

**Comment by tobisupreme** [comment]
Hi Oyin!

Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/).

I see that multiple files have been changed. I recommend that you create a different branch for a different change. 

I am here for you for the next 6 hours before I close the PR so you can initiate a new one which will be easier to merge.

**Comment by oyindamolaWbCode** [comment]
> Hi Oyin!
> 
> Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/).
> 
> I see that multiple files have been changed. I recommend that you create a different branch for a different change.
> 
> I am here for you for the next 6 hours before I close the PR so you can initiate a new one which will be easier to merge.

I created a branch when I first solved a conflict, so I still use the same for other conflicts.

**Comment by oyindamolaWbCode** [comment]
> @oyindamolaWbCode Omoregbe Daniel is going to be duplicated. Can you fix this. As we are ready to merge this.

I removed one of the duplicated names.

**Pull request merged**
