### PR TITLE
Gideon added his name

### PR DESCRIPTION
**Pull request by getgiddy**

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
here can you fix the conflict still. I just merged some other PR

**Comment by getgiddy** [comment]
> here can you fix the conflict still. I just merged some other PR

Fixed @Oluwasetemi

**Comment by Oluwasetemi** [comment]
image

you have removed one name from the PR you are bringing ooo. code will break oh @getgiddy

**Comment by Oluwasetemi** [comment]
No I think you're good now. Can you confirm everything is okay?

**Comment by Oluwasetemi** [comment]
Your should be the 6th name.

**Comment by getgiddy** [comment]
> Your should be the 6th name.

Thank you

**Pull request merged**
