### PR TITLE
added my name to names.txt

### PR DESCRIPTION
**Pull request by de-marauder**
- Included my name to the names.txt file

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Review by tobisupreme — APPROVED** [review]

**Comment by de-marauder** [comment]
Yo tobi, can you assign this PR to me?

**Comment by tobisupreme** [comment]
How do you mean sir?

**Comment by de-marauder** [comment]
> How do you mean sir?

I just thought you could like select my username under the assignees section of this pic.

Screenshot from 2022-08-16 19-04-09


But nevermind it's not necessary

**Pull request merged**
