### PR TITLE
Feature: Autorefresh

### PR DESCRIPTION
**Pull request by YvonneDien**
- added autorefresh to index.html
- added autorefresh function to script.js

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
Any thoughts on this @tobisupreme @Omafovbe @Succynice

**Comment by Omafovbe** [comment]
Not necessary to me. We would have to review and merge `PR` before the list gets updated. Its not something that gets updated on the fly. Therefore i do not see the effect of this feature.

**Comment by tobisupreme** [comment]
I have no additions or takeaways!

**Comment by Succynice** [comment]
it's a nice feature, tho it would have less effect in this project, we still need to review and merge PR right.

@YvonneDien pls can you attach screenshots of this feature in action

**Pull request closed without merging**
