### PR TITLE
Added my name Ayoola Paul

### PR DESCRIPTION
**Pull request by Ayopal**
Learning how to contribute to open source from live class

### CODE REVIEW

**Comment by tobisupreme** [comment]
Hi Paul!

Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/).

To enable me to do this, READ the README again carefully, update your code with the latest and push the update. I am here for you for the next 6 hours before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Ayopal** [comment]
Thank you for your feedback.  I get to that now

**Comment by Ayopal** [comment]
How do i update my local.  I already did git pull but nothing changed

**Comment by Ayopal** [comment]
It says my branch is up to date with the origin

**Comment by tobisupreme** [comment]
I'm not sure. I recommend that you update the fork here on github, then make a fresh clone on your local computer, then follow the instas per the Readme.

We recommend that you work on a branch that is different from the main branch.

**Comment by Ayopal** [comment]
I already created a branch and send a new pull request Can you please confirm that

**Comment by tobisupreme** [comment]
The branch you have here is named `main`. 

Refer to the guide in the `README.md` file on this repository

**Pull request merged**
