### PR TITLE
added my contribution to the names list

### PR DESCRIPTION
**Pull request by spartan124**

### CODE REVIEW

**Comment by Succynice** [comment]
pls update your code

**Comment by spartan124** [comment]
> pls update your code

Thanks, I just did

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Oluwasetemi** [comment]
You have some file changes this will impact the current files we have. 

README.md is uopdated but we don't need it updated. 
names.txt will overwrite our names. 

You have a mystery file that end with q. I think something is not right.

**Comment by Oluwasetemi** [comment]
image

**Comment by spartan124** [comment]
> image

I pulled changes from upstream using "git pull upstream main". The additional  file changes came with the pull request I think. I had to manually merge the changes. I will proceed to delete the q file

**Comment by spartan124** [comment]
what should I do about the Readme file. How do I revert the changes?

**Comment by Oluwasetemi** [comment]
Can you close this PR and send another one?

**Review by spartan124 — COMMENTED** [review]
Is this okay?

**Pull request closed without merging**
