### PR TITLE
feat: Add Iniobong Benson to names.txt

### PR DESCRIPTION
**Pull request by linibensonjr**

### CODE REVIEW

**Review by Succynice — COMMENTED** [review]
can you please update your code by pulling the latest changes from the upstream.

```sh
git pull upstream main

git push origin main
```

**Comment by linibensonjr** [comment]
Hi @Succynice I've fixed this, thanks

**Comment by Succynice** [comment]
Sorry I wasn't available to merge your code, can you pull and push one more time

**Comment by linibensonjr** [comment]
> Sorry I wasn't available to merge your code, can you pull and push one more time

I've done that

**Review by Succynice — COMMENTED** [review]
I think your code is still a bit behind, pull again to get your code updated,

**Review by Succynice — APPROVED** [review]

**Pull request merged**
