### PR TITLE
Merge pull request #1 from Oluwasetemi/main

### PR DESCRIPTION
**Pull request by coderchris1234**
open-source

### CODE REVIEW

**Comment by tobisupreme** [comment]
This commit doesn't add or remove any lines! Can you please tell me about this PR?

**Comment by Oluwasetemi** [comment]
@coderchris1234 we noticed this PR does not include any name or file changes, what do you want us to do with it? We will close the PR in 6 hrs.

**Comment by tobisupreme** [comment]
Please refer to the README.md file then update your code with the latest and push the update. I am here for you for the next 6 hours before I close the PR so you can initiate a new one which will be easier to merge.

**Review by coderchris1234 — COMMENTED** [review]
I added my name to the name file

**Comment by Oluwasetemi** [comment]
We noticed that you name is not in the file you are attempting to merge. Kindly read the README as @tobisupreme  suggested. We await your response.

**Comment by Succynice** [comment]
Sorry I have to close this PR, kindly update your code and initiate a fresh PR

Cheers 🥂

**Pull request closed without merging**
