### PR TITLE
added my own name

### PR DESCRIPTION
**Pull request by litobalolu**

### CODE REVIEW

**Comment by Succynice** [comment]
Can you update your code and push again

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by litobalolu** [comment]
Oh, alright sir. I'll do that now

**Comment by litobalolu** [comment]
can you check if it's successful now sir? I kind of played around it a bit. I wasn't very sure If I was doing the right thing

**Comment by Oluwasetemi** [comment]
We still have a conflict here.

**Comment by litobalolu** [comment]
Okay. I'm going to create a new branch entirely and pull the current repository from the origin. Then I'll resolve the conflict and push it. Will that work?

**Comment by litobalolu** [comment]
this is what i have in my vscode.
image

**Pull request merged**
