### PR TITLE
Add name

### PR DESCRIPTION
**Pull request by Tifem**
added my name

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
You need to add just one name. You have 2 names in the PR.

**Review by tobisupreme — CHANGES_REQUESTED** [review]
Hi Bolu!

When you resolved the merge conflicts, you duplicated "Medina Folashade Adeniran".

It is currently on the line just above your name.

What I need you to do is to remove the name from the line above yours, and then we can merge your PR. 🙏

**Comment by tobisupreme** [comment]
If you look to the top-right corner, you will see an indicator that tells you how many lines were changed. 

What we want to achieve is to add your name. We see two green boxes which signify that you added two lines. Your name, and another which results in a duplicate

**Review by Tifem — COMMENTED** [review]
Removed Medina Folashade Name

**Review by tobisupreme — APPROVED** [review]

**Pull request merged**
