### PR TITLE
Added Temitope Agbaje to the list

### PR DESCRIPTION
**Pull request by TemitopeAgbaje**

### CODE REVIEW

**Comment by tobisupreme** [comment]
Thank you! We will merge this as soon as we treat the prior PRs. 

In a bid to avoid further merge conflicts, I recommend that you make another commit and remove your name from the last line and then add it anywhere else in between. Thanks again!

**Comment by tobisupreme** [comment]
Thank you! We will merge this as soon as we treat the prior PRs. 

In a bid to avoid further merge conflicts, I recommend that you make another commit and remove your name from the last line and then add it anywhere else in between. Thanks again!

**Comment by tobisupreme** [comment]
Thank you! We will merge this as soon as we treat the prior PRs. 

In a bid to avoid further merge conflicts, I recommend that you make another commit and remove your name from the last line and then add it anywhere else in between. Thanks again!

**Comment by tobisupreme** [comment]
Thank you! We will merge this as soon as we treat the prior PRs. 

In a bid to avoid further merge conflicts, I recommend that you make another commit and remove your name from the last line and then add it anywhere else in between. Thanks again!

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by TemitopeAgbaje** [comment]
Updated , Kindly review

**Comment by Oluwasetemi** [comment]
Please update again.

**Comment by Oluwasetemi** [comment]
Kindly update again. I ran some optimizations.

**Comment by Oluwasetemi** [comment]
Or create a new PR. Sorry for the inconvenience

**Comment by tobisupreme** [comment]
Merged in #569 🥳

**Pull request closed without merging**
