### PR TITLE
feat: :memo: AltSchool Logo

### PR DESCRIPTION
**Pull request by Omafovbe**
updated the AltSchool logo for light & dark modes

### CODE REVIEW

**Review by Succynice — COMMENTED** [review]
can you attach a screenshot showing the after effect of this changes on the `README`

**Comment by Omafovbe** [comment]
Here is the images demonstrating the change in the repo

altschool dark mode before
--How it looks now in dark mode

altschool dark mode after
--How it would look after the changes are effected in dark mode

altschool light mode after
-- How it would look in light mode

**Comment by Omafovbe** [comment]
Done. Replied the comment with the attached screenshot

**Comment by Succynice** [comment]
OMG this is great

**Pull request merged**
