### PR TITLE
added my name to names.txt file

### PR DESCRIPTION
**Pull request by Bukola-Testimony**
Hi Setemi. I added my name to the names.txt file. Thanks

### CODE REVIEW

**Comment by Succynice** [comment]
pls update your code to the latest

```sh
git pull upstream main

git push origin main
```

**Comment by Bukola-Testimony** [comment]
updated, so what do I do next?  Should I create a new pull request?

**Comment by Succynice** [comment]
your code is still behind, all you need is just pull from the base code to get the latest changes

use the first command I provided above, then use the second one to push back to the base repo

**Comment by Bukola-Testimony** [comment]
Done, all conflicts merged. kindly check,

**Review by Succynice — COMMENTED** [review]
nice one. but one more thing, you added an extra line at the button of the list, kindly remove it and you are good to go

**Comment by Bukola-Testimony** [comment]
Done.

**Pull request merged**
