### PR TITLE
Added Adetunji Igbatayo to list

### PR DESCRIPTION
**Pull request by TunjiDev**
Added my name to list

### CODE REVIEW

**Comment by Succynice** [comment]
can you update your code to the latest code

**Comment by TunjiDev** [comment]
> can you update your code to the latest code

How do u mean?

**Comment by TunjiDev** [comment]
> can you update your code to the latest code

It has been updated

**Comment by Succynice** [comment]
Cool, one more thing, resolve the conflict by removing the unnecessary lines

**Comment by TunjiDev** [comment]
> Cool, one more thing, resolve the conflict by removing the unnecessary lines

Done!

**Review by Succynice — APPROVED** [review]

**Pull request merged**
