### PR TITLE
added my name

### PR DESCRIPTION
**Pull request by KorkuTegbe**

### CODE REVIEW

**Comment by Succynice** [comment]
pls update your code

**Comment by KorkuTegbe** [comment]
How do you mean?

**Comment by Succynice** [comment]
Your code is conflicting with the code base, pull the latest changes from the base repository and push again

**Comment by KorkuTegbe** [comment]
Will do, thanks.

**Comment by Succynice** [comment]
alright, drop a comment when you are done

**Comment by KorkuTegbe** [comment]
done please

**Comment by KorkuTegbe** [comment]
https://github.com/Oluwasetemi/altschool-opensource-names/pull/237


here's the link. Was having difficulties so started all over. Hope it's not
an issue.

**Pull request merged**
