### PR TITLE
Wrote search contributors functionality

### PR DESCRIPTION
**Pull request by omobolajisonde**
Anticipating your review 🤞🏾.

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
This is great but can you think of any use case for this. Thank you for your contribution. Your code is senior dev standard. Come and teach me small.

**Comment by Oluwasetemi** [comment]
I thought this is cool but we can look at implementing frontend searching using JavaScript and nodejs. 


cc @Omafovbe @oseunabiola @Succynice @tobisupreme what do you all think?

**Comment by Omafovbe** [comment]
That's a pretty cool idea. And a feature that can make it more interactive

**Comment by Omafovbe** [comment]
@Oluwasetemi well, playing with the terminal to see if your name is on the list before trying to merge won't be the first thing to come on anyone's mind. but if this function can be applied on the webpage then it would be more exciting from both ends. Meaning those who want to show off and those who want to wish to check before want to go into sending `PR` to merge their name

**Comment by Oluwasetemi** [comment]
Can we have a plan for the UI implementation of the search and still merge this one.

**Comment by Omafovbe** [comment]
That can be done.

**Comment by omobolajisonde** [comment]
> I read thru again and I think this terminal search will be helpful to anyone who wants to run a check to see if their name is present before creating a PR to add their names.

Exactly Sir, this is the main purpose I decided to implement this. Also, I was trying to check for my friends names and going through the long list of names was kind of stressful.

**Comment by omobolajisonde** [comment]
> @Oluwasetemi well, playing with the terminal to see if your name is on the list before trying to merge won't be the first thing to come on anyone's mind. but if this function can be applied on the webpage then it would be more exciting from both ends. Meaning those who want to show off and those who want to check before going into sending `PR` to merge their name

True, but I think it shines when someone wants to search for their friends names or wants to confirm if someone they expect to have added his/her name really has. You get Sir/Ma?

**Comment by omobolajisonde** [comment]
> This is great but can you think of any use case for this. Thank you for your contribution. Your code is senior dev standard. Come and teach me small.

Thanks for the compliments, Boss @Oluwasetemi 🙌. I just think it shines when someone wants to search for their friends names or wants to confirm if someone they expect to have added his/her name really has.

Ahh 😅, I just applied what we've been taught in Nodejs plus a little research 🤲🏾. We are learning from you boss.

**Review by muhdibee — CHANGES_REQUESTED** [review]
Good job...
Please also add a `toLowercase() ` function to search query variable to handle the case of letters on line 19 like so:

``````
const searchQuery = answer.trim().toLowerCase();
````````

**Comment by muhdibee** [comment]
> > Good job... Please also add a `toLowercase() ` function to search query variable to handle the case of letters on line 19 like so:
> > ```
> > const searchQuery = answer.trim().toLowerCase();
> > ```
> 
> Hi, thanks for the compliments. I did this already in the filter method call back function.

You are welcome Sonde.

**Review by Oluwasetemi — APPROVED** [review]

**Pull request merged**
