### PR TITLE
added my name

### PR DESCRIPTION
**Pull request by Osaro-tfk**

### CODE REVIEW

**Review by Succynice — COMMENTED** [review]
can you update your code by pulling the latest changes from the upstream, then push again.

```sh
git pull upstream main

git push origin main
```

**Comment by Osaro-tfk** [comment]
I have resolved the conflict. Kindly take a look at the PR again.
Thanks!

**Comment by Succynice** [comment]
Cool, can you update your code one more time

**Comment by Osaro-tfk** [comment]
By that you mean I should pull and push?

**Comment by Succynice** [comment]
Exactly

**Comment by Succynice** [comment]
Pull, modify and push

**Comment by Osaro-tfk** [comment]
okay

**Comment by Osaro-tfk** [comment]
I've done that

Anything else?

**Review by Succynice — APPROVED** [review]

**Pull request merged**
