### PR TITLE
Added my name to the list of names

### PR DESCRIPTION
**Pull request by adekunleoloduero**

### CODE REVIEW

**Comment by oseunabiola** [comment]
Can you please update your code by pulling the latest code from the original repo?

```sh

git pull upstream main

git push origin main

```

**Comment by Succynice** [comment]
can you please update your code by pulling latest code from the upstream.

```console
git pull upstream main

git push origin main
```

**Comment by Succynice** [comment]
can you please update your code by pulling the latest code from the upstream.

```console
git pull upstream main

git push origin main
```

**Comment by adekunleoloduero** [comment]
I've updated the code. Please merge!

**Review by Succynice — COMMENTED** [review]
cool, can you remove the unnecessary lines and pull the latest one more time

**Review by Succynice — COMMENTED** [review]
remove duplicate names and you are good to go

**Comment by adekunleoloduero** [comment]
Duplicate names removed as stated. Thanks!

**Review by Succynice — APPROVED** [review]

**Comment by adekunleoloduero** [comment]
Thanks @Succynice

**Pull request merged**
