### PR TITLE
added spaces to breaks to avoid merge conflicts

### PR DESCRIPTION
**Pull request by danieltolani**

### CODE REVIEW

**Review by Succynice — COMMENTED** [review]
lol the fear of conflict

but you can go ahead and remove the spaces, I think all you need to do is update your code, append your name properly and push again.

**Comment by danieltolani** [comment]
> lol the fear of conflict
> 
> but you can go ahead and remove the spaces, I think all you need to do is update your code, append your name properly and push again.

Lol.. Thanks. But there are other pull requests that will still clash.

**Comment by danieltolani** [comment]
> lol the fear of conflict
> 
> but you can go ahead and remove the spaces, I think all you need to do is update your code, append your name properly and push again.

Lol.. Thanks. But there are other pull requests that will still clash.

**Comment by Succynice** [comment]
yea I get but the spaces won't look good on our base code 

conflicts are meant to be resolved right? lol

**Comment by danieltolani** [comment]
> yea I get but the spaces won't look good on our base code
> 
> conflicts are meant to be resolved right? lol

image
First few codes had spaces.. I think the author will be able to remove spaces after merging with no conflicts?

**Comment by Succynice** [comment]
give me a sec

**Comment by danieltolani** [comment]
> give me a sec

Okay

**Comment by Succynice** [comment]
I tried resolving from my end but it just keeps loading, Network issue I suppose

**Comment by danieltolani** [comment]
Welll

**Comment by Succynice** [comment]
I believe it would be seamless from your end, just try chief

**Comment by danieltolani** [comment]
Are you free for a call?

**Comment by Succynice** [comment]
yea sure

**Comment by danieltolani** [comment]
https://meet.google.com/qbi-xiqu-zzw

**Pull request merged**
