### PR TITLE
Add Olanreaju Kabiru to the list of names and created contributorsLis…

### PR DESCRIPTION
**Pull request by olakayCoder1**
…tGithubApi HTML file

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
you have to clean it up and come up with 2 PR. Do you know how to achieve this?

**Comment by olakayCoder1** [comment]
I don't get what you meant by this "you have to clean it up and come up with 2 PR. Do you know how to achieve this?"

**Comment by Oluwasetemi** [comment]
Good.

Create two different branch for this changes. One branch to add your name. Send the PR from that branch. 

The second branch should be the branch to implement this contributionsList feature. Send the PR separately as well.

**Comment by Oluwasetemi** [comment]
You can checkout to the new 2 branches from this branch and delete the changes you don't want in each branch and commit and make PR.

**Comment by olakayCoder1** [comment]
Okay, I will do that tonight

**Pull request merged**
