### PR TITLE
Abdulbasit Yusuf added his name

### PR DESCRIPTION
**Pull request by Jideotetic**
Kindly review and add my name to the altschool-opensource-names

### CODE REVIEW

**Comment by oseunabiola** [comment]
Fix conflict. Pull from upstream

**Comment by Jideotetic** [comment]
How do you mean @oseunabiola

**Comment by Oluwasetemi** [comment]
You have to update your code because we have merged some other names.

**Comment by Jideotetic** [comment]
i have done that

**Pull request merged**
