### PR TITLE
Added name, Esther Ibom

### PR DESCRIPTION
**Pull request by Ibom99**
Esther Ibom was added to the `names.txt` file.

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Ibom99** [comment]
Hello good evening,
I’ve updated the code and made a new PR. Would be looking forward to being
merged without conflict this time around, haha.

Best regards ,
Esther

**Comment by Oluwasetemi** [comment]
Please update one more time.

**Comment by Ibom99** [comment]
It has been merged already as #574

**Comment by Oluwasetemi** [comment]
great

**Pull request closed without merging**
