### PR TITLE
Added Omafovbe

### PR DESCRIPTION
**Pull request by Omafovbe**
Added my name to the list

### CODE REVIEW

**Comment by Omafovbe** [comment]
Finally learnt a thing or two when faced with conflicts

**Comment by oseunabiola** [comment]
Interesting. One thing I also learn is to always pull before pushing.

You'd have to pull afresh to resolve the conflict.

**Comment by Omafovbe** [comment]
Resolved conflicts in the request

**Comment by Omafovbe** [comment]
Done

**Pull request merged**
