### PR TITLE
I added my name - Sharafdeen Quadri

### PR DESCRIPTION
**Pull request by Olalekan2040-slack**

### CODE REVIEW

**Review by Succynice — COMMENTED** [review]
Kindly remove the unnecessary lines that does not contain a character

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Oluwasetemi** [comment]
please update or create a new PR

**Comment by tobisupreme** [comment]
Hello Sharafdeen!

Please open a new PR! Remember to [make a branch](https://github.com/Oluwasetemi/altschool-opensource-names#make-a-branch) as you work on your changes!

We look forward to merging your next PR! 🥳

**Comment by Olalekan2040-slack** [comment]
Acknowledged. Kindly forgive me for the late response. I saw the message
late.

**Pull request closed without merging**
