### PR TITLE
Temiloluwa Onaleye

### PR DESCRIPTION
**Pull request by Temiloluwa-Onaleye**
Screenshot 2022-08-07 at 07 11 50

### CODE REVIEW

**Comment by Succynice** [comment]
please kindly update your code ny pulling the latest changes from the upstream, then push again.

```sh
git pull upstream main

git push origin main
```

**Comment by Succynice** [comment]
please kindly update your code by pulling the latest changes from the upstream, then push again.

```sh
git pull upstream main

git push origin main
```

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Succynice** [comment]
Sorry I have to close this PR, kindly update your code and initiate a fresh PR

Cheers 🥂

**Pull request closed without merging**
