### PR TITLE
I added My Name Salaudeen Mohammed Bashir

### PR DESCRIPTION
**Pull request by Basheer-Ade**

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Basheer-Ade** [comment]
Good evening! Followed the steps but it keep showing “names.txt” need to
merge. This happened after I created a branch and tried “git checkout (new
name).

**Comment by Basheer-Ade** [comment]
I created another PR and have sent it to you for approval/merging.

Thanks.

**Comment by Oluwasetemi** [comment]
Please update

**Comment by Basheer-Ade** [comment]
Update? What am I going to do?

**Comment by Oluwasetemi** [comment]
git pull upstream main

**Comment by Oluwasetemi** [comment]
git push -u

**Comment by Oluwasetemi** [comment]
You still have some conflicts. 

image

remove all the line with >>>>>> and <<<<<<.

Just your name should be in the PR

**Comment by Basheer-Ade** [comment]
Sir! I’m totally confused

And I followed every steps

Been on my system for 5 hours now I still don’t get it

This thing is hard

**Comment by Basheer-Ade** [comment]
Sir please after I typed this is shows “Automatic Merge Failed”

I’m still on the new branch I created

**Pull request merged**
