### PR TITLE
I added my name

### PR DESCRIPTION
**Pull request by Allename**
I added my name

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
can you update your code by pulling the latest I just merge #1

**Comment by Oluwasetemi** [comment]
Awesome

**Comment by Oluwasetemi** [comment]
but you left me with lot of comment and conflicts

**Comment by Allename** [comment]
> 

I didn't know how to deal with them
I thought if I committed and pushed it'll solve it🥶

**Comment by Oluwasetemi** [comment]
finally...good work.

**Comment by Allename** [comment]
Thank you😅

**Pull request merged**
