### PR TITLE
Add my name

### PR DESCRIPTION
**Pull request by Succynice**

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
cool work. thanks for the README.md. Pull the latest code. 🧑‍💻 You're doing well.

**Comment by Oluwasetemi** [comment]
can you remove the unnecessary lines and pull the latest one more time.

**Comment by Oluwasetemi** [comment]
Once you remove the empty lines you are good to go.

**Comment by Succynice** [comment]
I have removed them all

**Comment by Oluwasetemi** [comment]
@oseunabiola can you pull this into your end and update it or should we do it together?

**Review by oseunabiola — APPROVED** [review]
Approved

**Comment by oseunabiola** [comment]
> @oseunabiola can you pull this into your end and update it or should we do it together?

Just reading this. Let's do it together.

**Comment by Oluwasetemi** [comment]
@oseunabiola @Succynice 

To join the video meeting, click this link: https://meet.google.com/qpq-hhyv-fgs
Otherwise, to join by phone, dial +1 706-750-9736 and enter this PIN: 260 974 564#
To view more phone numbers, click this link: https://tel.meet/qpq-hhyv-fgs?hs=5

**Pull request merged**
