### PR TITLE
Update: Added my name to the student list

### PR DESCRIPTION
**Pull request by adeyinkaoresanya**

### CODE REVIEW

**Comment by Succynice** [comment]
pls can you update your code

**Comment by adeyinkaoresanya** [comment]
Hello Success, I have resolved the conflict. kindly approve merge.

**Comment by adeyinkaoresanya** [comment]
> pls can you update your code

Hello Success, I have resolved the conflict. Please kindly approve merge

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by adeyinkaoresanya** [comment]
Thank you for your message. I decided to start afresh by creating another branch and opening a new pull request, this time according to the contributing guide.

**Pull request closed without merging**
