### PR TITLE
i added my name

### PR DESCRIPTION
**Pull request by taofeekogungbade**

### CODE REVIEW

**Review by Succynice — COMMENTED** [review]
can you update your code by pulling the latest changes from the upstream, then push again.

```sh
git pull upstream main

git push origin main
```

**Comment by taofeekogungbade** [comment]
> can you update your code by pulling the latest changes from the upstream, then push again.
> 
> ```shell
> git pull upstream main
> 
> git push origin main
> ```



> can you update your code by pulling the latest changes from the upstream, then push again.
> 
> ```shell
> git pull upstream main
> 
> git push origin main
> ```

I pulled the latest changes though, can you please explain what the issue is?

**Comment by Succynice** [comment]
cool, it was perfect but I wasn't available to merge your code, sorry about that.

can you repeat the process one more time

**Comment by tobisupreme** [comment]
Hello Taofeek!

We are sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/).

To enable us to do this, READ the README again carefully, update your code with the latest and push the update. We are here for you for the next 6 hours before we close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Succynice** [comment]
Sorry I have to close this PR, kindly update your code and initiate a fresh PR

Cheers 🥂

**Pull request closed without merging**
