### PR TITLE
Added Popoola Emmanuel to the list of names

### PR DESCRIPTION
**Pull request by Gifted-Dev**
I was able to add my name: **POPOOLA EMMANUEL** to the middle of the names

### CODE REVIEW

**Comment by Oluwasetemi** [comment]
Please I am sorry for all the trouble we have caused you but count it all joy. Your PR is about to be merged and you will be able to see your name on this [url](https://altschool-opensource-names.oluwasetemi.dev/). 

To enable me to do this, **READ the README again carefully**, update your code with the latest and push the update. I am here for you for the next **6 hours** before I close the PR so you can initiate a fresh PR which will be easier to merge.

**Comment by Gifted-Dev** [comment]
How do I update my code to the latest, do I have to refork?

**Comment by Oluwasetemi** [comment]
git pull upstream main 


git push origin <your branch name>

**Comment by Gifted-Dev** [comment]
I hope this works fine.. 😁... or I try again 😪

**Comment by Oluwasetemi** [comment]
You are almost there. Remove all the >>>>>> and <<<<< signs. Just your name.

**Comment by Oluwasetemi** [comment]
image
remove line 25, 27 - 29. Duplicate and conflicts.

**Comment by Gifted-Dev** [comment]
oh I didn't see that.. Let me check it.. Breathes in heavily!

**Comment by Gifted-Dev** [comment]
How about now sir?

**Pull request merged**
